name: Code quality

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check lints
        run: cargo clippy --all-targets --all-features -- -D warnings

  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check formatting
        run: cargo fmt --all --check
