name: Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

  ALICE_USERNAME: alice
  ALICE_PASSWORD: y0zHDHwv3X31
  BOB_USERNAME: bob
  BOB_PUBLIC_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMmZ7gtoEsZDA8DqofQbYnXfKxXUNJsWuOum35x2Yr4C
  BOB_PRIVATE_KEY: >
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDJme4LaBLGQwPA6qH0G2J13ysV1DSbFrjrpt+cdmK+AgAAAJjlF8fM5RfH
    zAAAAAtzc2gtZWQyNTUxOQAAACDJme4LaBLGQwPA6qH0G2J13ysV1DSbFrjrpt+cdmK+Ag
    AAAEBF07KN5z24CX3MeVVUx7F7nF77CwxV4hKwGqRfRwKRlMmZ7gtoEsZDA8DqofQbYnXf
    KxXUNJsWuOum35x2Yr4CAAAADkNJIGRlcGxveW1lbnRzAQIDBAUGBw==
    -----END OPENSSH PRIVATE KEY-----

jobs:
  ssh-image:
    name: ssh
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      prefix: ssh
      context: docker/ssh
      dockerfile: docker/ssh/Dockerfile

  ettac-image:
    name: ettac
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      prefix: ettac
      context: .
      dockerfile: docker/build/Dockerfile
      paths: |
        Cargo.lock
        src/**/*.rs

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Load cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binaries
        run: cargo build

  format:
    name: Formatting
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v6

      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Lints
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v6

      - name: Check lints
        run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v6

      - name: Load cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [ ssh-image, build ]

    services:
      alice:
        image: ghcr.io/${{ github.repository }}:${{ needs.ssh-image.outputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports: [ 7022:22 ]
        env:
          USERNAME: ${{ env.ALICE_USERNAME }}
          PASSWORD: ${{ env.ALICE_PASSWORD }}

      bob:
        image: ghcr.io/${{ github.repository }}:${{ needs.ssh-image.outputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports: [ 7122:22 ]
        env:
          USERNAME: ${{ env.BOB_USERNAME }}
          PUBLIC_KEY: ${{ env.BOB_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v6

      - name: Wait for SSH servers
        run: |
          timeout 120s sh -c 'until nc -z localhost 7022; do sleep 0.1; done'
          timeout 120s sh -c 'until nc -z localhost 7122; do sleep 0.1; done'

      - name: Load cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --features integration

  test-image:
    name: Test image
    runs-on: ubuntu-latest
    needs: [ ssh-image, ettac-image, integration ]

    services:
      with-password:
        image: ghcr.io/${{ github.repository }}:${{ needs.ssh-image.outputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports: [ 7022:22 ]
        env:
          USERNAME: ${{ env.ALICE_USERNAME }}
          PASSWORD: ${{ env.ALICE_PASSWORD }}

      with-public-key:
        image: ghcr.io/${{ github.repository }}:${{ needs.ssh-image.outputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports: [ 7122:22 ]
        env:
          USERNAME: ${{ env.BOB_USERNAME }}
          PUBLIC_KEY: ${{ env.BOB_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v6

      - name: Wait for SSH servers
        run: |
          timeout 120s sh -c 'until nc -z localhost 7022; do sleep 0.1; done'
          timeout 120s sh -c 'until nc -z localhost 7122; do sleep 0.1; done'

      - name: Run a recipe
        run: |
          docker run --rm \
            --network host \
            --volume "$(pwd)/examples:/examples" \
            --volume "$(pwd)/examples/empty.lua:/deploy.lua" \
            --env PASSWORD="${{ env.ALICE_PASSWORD }}" \
            --env PRIVATE_KEY="${{ env.BOB_PRIVATE_KEY }}" \
            ghcr.io/${{ github.repository }}:${{ needs.ettac-image.outputs.tag }} \
            \
            with-password with-public-key
